name: Cloud Gaming Windows Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Activer le Bureau à Distance (RDP)
      run: |
        Set-ItemProperty "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      shell: powershell

    - name: Installer Apache Guacamole
      run: |
        Invoke-WebRequest -Uri "https://archive.apache.org/dist/guacamole/1.5.0/binary/guacamole-1.5.0.war" -OutFile guacamole.war
        New-Item -ItemType Directory -Path "C:\Guacamole" -Force
        Move-Item -Path guacamole.war -Destination "C:\Guacamole\guacamole.war"
      shell: powershell

    - name: Configurer le serveur web pour Guacamole
      run: |
        $tomcatUrl = "https://archive.apache.org/dist/tomcat/tomcat-10/v10.1.14/bin/apache-tomcat-10.1.14-windows-x64.zip"
        $tomcatZip = "tomcat.zip"
        $tomcatDir = "C:\Tomcat"
        
        Invoke-WebRequest -Uri $tomcatUrl -OutFile $tomcatZip
        Expand-Archive -Path $tomcatZip -DestinationPath $tomcatDir -Force
        
        if (Test-Path "$tomcatDir\bin\startup.bat") {
          Move-Item -Path "C:\Guacamole\guacamole.war" -Destination "$tomcatDir\webapps\"
          Start-Process -FilePath "$tomcatDir\bin\startup.bat" -NoNewWindow -Wait
        } else {
          Write-Host "Erreur : Tomcat n'a pas été extrait correctement."
          exit 1
        }
      shell: powershell

    - name: Installer Cloudflare Tunnel
      run: |
        Invoke-WebRequest -Uri "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" -OutFile cloudflared.exe
        Start-Process -NoNewWindow -FilePath .\cloudflared.exe -ArgumentList "tunnel --url http://localhost:8080" -Wait
      shell: powershell

    - name: Installer Google Chrome
      run: |
        Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile chrome_installer.exe
        Start-Process -FilePath chrome_installer.exe -ArgumentList "/silent /install" -NoNewWindow -Wait
      shell: powershell

    - name: Garder le serveur actif
      run: |
        ping -t localhost
      shell: cmd
